<?xml version="1.0" encoding="utf-8"?><Database Name="Document" Class="DocumentDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\ZAO;Initial Catalog=Document;Integrated Security=True" SettingsObjectName="NjitSoftware.Properties.Settings" SettingsPropertyName="DocumentConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Document" Member="Documents">
    <Type Name="Document">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ArchiveDocumentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Data" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>