//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Elegant.Ui.CommandSourceAttribute("Njit.Program.ApplicationCommands", "Njit.Program.ApplicationCommands")]

namespace Njit.Program
{
    //  This class is required for commands suppport.
    // Do not modify this code inside the editor.

    public class ApplicationCommands
    {

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
        public static Elegant.Ui.Command ExitCommand = new Elegant.Ui.Command("ExitCommand");
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
        public static Elegant.Ui.Command ProgramSettingShowCommand = new Elegant.Ui.Command("ProgramSettingShowCommand");
    }
}
